/**
 * Seed script: Inserts WASSCE/NECO syllabus-aligned lessons for SS1-SS3.
 *
 * Usage:
 *   npx tsx scripts/seed-lessons.ts
 *
 * Requires DATABASE_URL env var (loaded from .env or set in environment).
 */

import { neon } from '@neondatabase/serverless';

const sql = neon(process.env.DATABASE_URL!);

// ─── Syllabus data ───────────────────────────────────────────────────────────
// Each topic is mapped to the WAEC/NECO scheme of work for that class.

interface LessonDef {
  topic: string;
  body: string;
}

const COMMERCIAL = 'Commercial';
const SCIENCE   = 'Science';
const TECH      = 'Tech';
const ARTS      = 'Arts';

function departmentOf(subject: string): string {
  if (['Commerce','Accounting','Economics','Business Studies'].includes(subject)) return COMMERCIAL;
  if (['Biology','Chemistry','Physics','Mathematics'].includes(subject)) return SCIENCE;
  if (['Basic Technology','Computer Studies','Technical Drawing'].includes(subject)) return TECH;
  if (['English Language','Literature-in-English','Government','History','Christian Religious Studies'].includes(subject)) return ARTS;
  throw new Error(`Unknown subject: ${subject}`);
}

// ─── SS1 ─────────────────────────────────────────────────────────────────────

const SS1: Record<string, LessonDef[]> = {
  Commerce: [
    { topic: 'Meaning and Scope of Commerce',
      body: `<p>Commerce is defined as the study of trade and aids to trade. It involves the distribution of goods and services from producers to consumers. The WAEC syllabus expects students to distinguish between commerce, trade, and industry, and to understand the relationship between commerce and other business subjects such as economics and accounting.</p><p>Production is classified into primary (extractive), secondary (manufacturing), and tertiary (services). Commerce falls under tertiary production because it facilitates the exchange of goods and services. Key concepts covered include barter trade, the evolution of money, and the chain of distribution (producer → wholesaler → retailer → consumer).</p><p>Students should be able to: (i) define commerce; (ii) explain the scope of commerce; (iii) differentiate between trade and commerce; (iv) outline the functions of commerce in national development.</p>` },
    { topic: 'Occupations and Production',
      body: `<p>This topic introduces the concept of occupation — any legal activity a person engages in to earn a living. Occupations are classified into industrial (directly involved in production) and commercial (facilitate distribution).</p><p>Production is the creation of utility — form utility (manufacturing), place utility (transportation), time utility (storage), and possession utility (exchange). The factors of production — land, labour, capital, and entrepreneur — are examined. WAEC questions often ask about the characteristics and rewards of each factor: rent, wages, interest, and profit.</p><p>Revision emphasis: discuss the importance of division of labour and specialization in increasing productivity.</p>` },
  ],
  Accounting: [
    { topic: 'Introduction to Accounting — Principles and Concepts',
      body: `<p>Accounting is defined as the process of identifying, measuring, recording, classifying, summarizing, and communicating financial information. The WAEC syllabus emphasizes the accounting concepts: business entity, going concern, consistency, accrual, prudence, materiality, and historical cost.</p><p>The accounting equation (Assets = Capital + Liabilities) forms the foundation of double-entry bookkeeping. Every transaction has a dual effect — a debit and a credit. Students must be able to classify accounts into personal, real, and nominal categories and apply the rules of debit and credit accordingly.</p>` },
    { topic: 'Source Documents and Books of Original Entry',
      body: `<p>Source documents are the evidence for financial transactions. The WAEC/NECO syllabus identifies: receipts, invoices (purchases and sales), debit/credit notes, payment vouchers, and bank tellers.</p><p>The books of original entry (subsidiary books) include: Sales Journal, Purchases Journal, Returns Inwards/Outwards Journals, Cash Book, and General Journal. Students must understand the purpose of each book and the posting process to the general ledger. Examination questions often require preparation of a three-column cash book and the posting of entries.</p>` },
  ],
  Economics: [
    { topic: 'Basic Concepts of Economics — Scarcity and Choice',
      body: `<p>Economics is the study of human behaviour in allocating scarce resources to satisfy unlimited wants. WAEC defines scarcity as the limited supply of resources relative to demand. This leads to choice and opportunity cost — the value of the next best alternative foregone.</p><p>The production possibility curve (PPC) illustrates scarcity, choice, opportunity cost, and economic growth. Students should be able to draw and interpret PPC diagrams. The basic economic problems — what to produce, how to produce, and for whom to produce — are addressed differently in capitalist, socialist, and mixed economies.</p>` },
    { topic: 'Demand and Supply',
      body: `<p>Demand is the quantity of a commodity consumers are willing and able to purchase at various prices in a given period. The law of demand states that price and quantity demanded are inversely related (ceteris paribus). Supply is the quantity producers are willing to offer at various prices, and the law of supply states a direct relationship.</p><p>WAEC expects students to distinguish between movement along (extension/contraction) and shift (increase/decrease) of demand/supply curves, and to identify factors causing shifts. Equilibrium price is determined at the intersection of demand and supply. The concept of price controls (minimum and maximum prices) is examined with diagrams.</p>` },
  ],
  'Business Studies': [
    { topic: 'The Nature and Forms of Business Organizations',
      body: `<p>Business Studies covers the formation, structure, and management of businesses. The WAEC syllabus identifies forms: sole proprietorship, partnership, private and public limited companies, cooperatives, and public corporations.</p><p>Students must compare these forms on: ownership, capital sources, decision-making, liability, profit-sharing, advantages, and disadvantages. The concept of limited liability and the distinction between a company and a partnership are frequently tested. The lesson also introduces business objectives — profit, growth, survival, and social responsibility.</p>` },
    { topic: 'The Office — Functions and Equipment',
      body: `<p>The office is defined as a room or building where administrative work is carried out. WAEC categorizes office functions into primary (receiving information, recording, arranging meetings) and secondary (filing, mailing, reprography, security).</p><p>Office equipment — computers, printers, photocopiers, scanners, and filing cabinets — are studied with their uses. Modern office technology (email, video conferencing, cloud storage) is emphasized. Students should be able to recommend appropriate equipment for given office tasks.</p>` },
  ],
  Biology: [
    { topic: 'Classification of Living Organisms',
      body: `<p>Biology begins with the classification of living things into five kingdoms: Monera (bacteria), Protista (protozoa), Fungi (mushrooms, moulds), Plantae (plants), and Animalia (animals). WAEC emphasizes the binomial system of nomenclature (Genus species).</p><p>The characteristics of each kingdom and examples of major phyla are covered. Students learn taxonomic hierarchy: Kingdom → Phylum → Class → Order → Family → Genus → Species. Practical identification of organisms using simple keys is an essential skill for the WAEC practical examination.</p>` },
    { topic: 'The Cell — Structure and Organization',
      body: `<p>The cell is the basic unit of life. WAEC/NECO requires students to know the structure and functions of cell organelles: nucleus, mitochondria, ribosomes, endoplasmic reticulum, Golgi apparatus, lysosomes, chloroplasts (plants), and cell wall (plants).</p><p>Differences between plant and animal cells are tabulated. Levels of organization: cells → tissues → organs → systems → organisms. The concept of cell specialization (e.g., nerve cells, red blood cells, root hair cells) is explained. Students draw and label typical plant and animal cells as seen under the light microscope.</p>` },
  ],
  Chemistry: [
    { topic: 'Introduction to Chemistry — Particulate Nature of Matter',
      body: `<p>Chemistry is the study of matter and its transformations. The WAEC syllabus begins with the particulate nature of matter — matter is made of atoms, molecules, and ions. The kinetic theory explains the behaviour of solids, liquids, and gases in terms of particle arrangement and movement.</p><p>Students learn about changes of state (melting, boiling, evaporation, condensation, sublimation) at the particle level. Diffusion and Brownian motion are presented as evidence for the particulate nature. Laboratory safety rules and common apparatus (beakers, flasks, test tubes, Bunsen burners) are introduced with their uses.</p>` },
    { topic: 'Chemical Symbols, Formulae, and Equations',
      body: `<p>WAEC expects students to write correct symbols for elements and chemical formulae for compounds. Valency is introduced to determine formula writing. Common ions (Na⁺, K⁺, Ca²⁺, Cl⁻, SO₄²⁻, NO₃⁻) must be memorized.</p><p>Balancing chemical equations is a core skill — the number of atoms of each element must be equal on both sides. Types of chemical reactions: combination, decomposition, displacement, and double decomposition (precipitation). Students practice writing and balancing equations for these reactions.</p>` },
  ],
  Physics: [
    { topic: 'Measurement and Fundamental Quantities',
      body: `<p>Physics begins with measurement — the foundation of all experimental science. The WAEC syllabus covers fundamental quantities (mass, length, time, electric current, temperature, luminous intensity, amount of substance) and their SI units. Derived quantities (area, volume, density, velocity, acceleration, force) are derived from fundamental quantities.</p><p>Measuring instruments — metre rule, vernier calliper, micrometer screw gauge, stopwatch, measuring cylinder, and thermometer — are studied with their least counts and reading procedures. Estimation of errors and significant figures are introduced to prepare students for practical examinations.</p>` },
    { topic: 'Motion — Speed, Velocity, and Acceleration',
      body: `<p>Motion is studied under linear kinematics. Distance and displacement, speed and velocity, and acceleration are defined. WAEC requires students to distinguish between scalar and vector quantities. The equations of motion for uniformly accelerated bodies are derived: v = u + at, s = ut + ½at², v² = u² + 2as.</p><p>Graphical analysis of motion — distance-time and velocity-time graphs — are interpreted. The slope of a distance-time graph gives speed; the slope of a velocity-time graph gives acceleration; the area under a velocity-time graph gives displacement.</p>` },
  ],
  Mathematics: [
    { topic: 'Number Systems and Numeration',
      body: `<p>The number system: natural numbers (ℕ), integers (ℤ), rational numbers (ℚ), irrational numbers, and real numbers (ℝ). WAEC emphasizes operations with integers, fractions, decimals, and percentages.</p><p>Indices (laws of indices), logarithms (characteristic and mantissa using logarithm tables), and surds (simplification, rationalization) are covered. Students apply these to solve problems involving growth, decay, and compound interest. Standard form (scientific notation) is used for very large and very small numbers.</p>` },
    { topic: 'Algebra — Simplification and Equations',
      body: `<p>Algebraic manipulation is a core WAEC topic. Students expand, factorize, and simplify algebraic expressions. Linear equations in one and two variables are solved, including simultaneous equations (elimination and substitution methods).</p><p>Quadratic equations are solved by factorization, completing the square, and the quadratic formula (x = [-b ± √(b² - 4ac)] / 2a). The discriminant (b² - 4ac) determines the nature of roots. Word problems are translated into algebraic equations and solved.</p>` },
  ],
  'Basic Technology': [
    { topic: 'Workshop Safety and Hand Tools',
      body: `<p>Basic Technology emphasizes safety as the first priority. WAEC syllabus covers workshop safety rules — proper attire, handling of tools, fire extinguishers, first aid, and accident prevention. Common hazards and safety signs are identified.</p><p>Hand tools for woodwork (saws, planes, chisels, hammers), metalwork (files, hacksaws, centre punches, taps, dies), and basic electrical work (pliers, screwdrivers, wire strippers) are introduced with their correct uses and maintenance. Students learn to select the appropriate tool for a specific job.</p>` },
    { topic: 'Materials — Wood, Metals, and Plastics',
      body: `<p>Engineering materials are classified into wood (hardwood and softwood), metals (ferrous and non-ferrous), plastics (thermoplastics and thermosets), and ceramics. WAEC expects knowledge of the properties (strength, hardness, ductility, malleability, conductivity) and common uses of each material.</p><p>Wood: sources, seasoning methods (air and kiln), and defects. Metals: properties of steel, aluminium, copper, and brass. Plastics: common types (PVC, polythene, nylon, Perspex) and their applications. Environmental impact of material disposal is briefly discussed.</p>` },
  ],
  'Computer Studies': [
    { topic: 'History and Generations of Computers',
      body: `<p>Computer Studies introduces the evolution of computing devices — from abacus to Napier's bones, slide rule, Pascal's calculator, Babbage's analytical engine, and modern electronic computers.</p><p>Generations: First (vacuum tubes — ENIAC, UNIVAC), Second (transistors), Third (integrated circuits), Fourth (microprocessors), and Fifth (artificial intelligence). Each generation brought increases in speed, memory, reliability, and reductions in size and cost. WAEC questions often require matching devices to generations and comparing characteristics.</p>` },
    { topic: 'Computer Hardware — Input, Output, and Storage',
      body: `<p>Hardware refers to the physical components of a computer system. The WAEC syllabus covers input devices (keyboard, mouse, joystick, scanner, microphone, touchscreen), output devices (monitor, printer — dot matrix, inkjet, laser, plotter, speaker), and storage devices (hard disk, SSD, flash drive, CD/DVD, memory card).</p><p>Students learn to differentiate between primary memory (RAM, ROM) and secondary storage, and to compare storage capacities and speeds. The central processing unit (CPU) — control unit, arithmetic logic unit (ALU), and registers — is explained with a basic block diagram.</p>` },
  ],
  'Technical Drawing': [
    { topic: 'Drawing Instruments and Basic Linework',
      body: `<p>Technical Drawing (TD) is the language of engineers and architects. WAEC requires students to be proficient with the drawing board, T-square, set squares (30°/60° and 45°), compass, dividers, protractor, and scale ruler.</p><p>Types of lines: visible outlines (continuous thick), hidden details (dashed), centre lines (chain thin), dimension lines (continuous thin with arrows), section lines (continuous thin at 45°). Lettering — upper/lower case, single stroke, and the ratio of height to width — must follow standardized conventions. Students produce title blocks and borders.</p>` },
    { topic: 'Geometric Constructions',
      body: `<p>Geometric constructions are fundamental to TD. WAEC expects students to construct: bisection of lines and angles, perpendicular and parallel lines, division of lines into equal parts, construction of angles (30°, 45°, 60°, 75°, 90°, 120°) without a protractor.</p><p>Constructing regular polygons — equilateral triangle, square, pentagon, hexagon, octagon — using compass and ruler. Circles — finding the centre, drawing tangents, constructing inscribed and circumscribed polygons. These skills are essential for later topics (projections, building drawing).</p>` },
  ],
  'English Language': [
    { topic: 'Essay Writing — Types and Structure',
      body: `<p>The WAEC/NECO English Language examination requires students to write well-structured essays. Four main types: narrative (telling a story), descriptive (painting a picture with words), expository (explaining a process or idea), and argumentative (presenting a case for or against a proposition).</p><p>The standard essay structure — introduction (thesis statement), body (paragraphs with topic sentences and supporting details), and conclusion (summary and final thought) — is drilled. Students learn to use transitional words and to vary sentence structure for effect. Time management: 45 minutes per essay in the examination.</p>` },
    { topic: 'Comprehension — Reading and Answering Questions',
      body: `<p>Comprehension passages test the ability to read, understand, and interpret written texts. WAEC questions typically test: (i) the meaning of words and phrases in context, (ii) the main idea and supporting details, (iii) inference and deduction, (iv) the author's attitude and purpose, (v) summarizing specific points.</p><p>Techniques: preview the questions before reading the passage, scan for key words, read actively with a pencil, answer in complete sentences using your own words unless quoting is specified. Common pitfalls are copying verbatim and misinterpreting figurative expressions.</p>` },
  ],
  'Literature-in-English': [
    { topic: 'Introduction to Literature — Genres and Functions',
      body: `<p>Literature is the creative expression of human experiences through language. The three main genres: prose (fiction — novels, short stories), drama (plays intended for performance), and poetry (rhythmic, condensed expression). WAEC/NECO examination includes questions on all three genres.</p><p>Functions of literature: entertainment, education, cultural preservation, social criticism, and moral instruction. Students learn basic literary terms — theme, plot, character, setting, conflict, point of view, diction, and figurative language (simile, metaphor, personification, irony). The recommended texts for the year are announced at the beginning of the session.</p>` },
    { topic: 'Elements of Poetry',
      body: `<p>Poetry is distinguished by its form, sound devices, and figurative language. WAEC expects students to identify and explain: rhyme scheme, rhythm, meter (iamb, trochee, etc.), alliteration, assonance, onomatopoeia, repetition, and enjambment.</p><p>Imagery — visual, auditory, olfactory, tactile, gustatory — creates vivid mental pictures. Poetic devices: simile, metaphor, personification, hyperbole, irony, symbolism. Students analyze prescribed poems for the poet's mood, tone, and theme, and write critical essays supported by textual evidence.</p>` },
  ],
  Government: [
    { topic: 'Basic Concepts of Government',
      body: `<p>Government is defined as the institution through which a state exercises authority and makes binding decisions. WAEC focuses on the concepts of power (the ability to influence behaviour), authority (legitimate power), legitimacy (acceptance of authority by the governed), and sovereignty (supreme power within a territory).</p><p>Functions of government: law-making, law enforcement, defence, foreign relations, economic management, and social welfare. The state is defined as a politically organized body with a defined territory, population, government, and sovereignty. Distinguish between a state and a nation.</p>` },
    { topic: 'Types and Forms of Government',
      body: `<p>WAEC syllabus classifies governments by: (i) structure — unitary vs. federal, (ii) relationship between executive and legislature — presidential vs. parliamentary, (iii) ideology — democracy vs. authoritarianism, (iv) location of power — monarchy vs. republic.</p><p>Democracy is defined as government of the people, by the people, for the people. Features: periodic elections, rule of law, fundamental rights, independent judiciary. The merits and demerits of each form are compared, with reference to Nigeria's federal presidential system.</p>` },
  ],
  History: [
    { topic: 'Pre-Colonial Nigerian Societies',
      body: `<p>The WAEC History syllabus requires knowledge of major pre-colonial states and empires. The Oyo Empire dominated the Yoruba region with its cavalry and trade. The Benin Kingdom was renowned for its art and administration. The Hausa city-states (Kano, Katsina, Zaria) thrived through trans-Saharan trade. The Kanem-Bornu Empire controlled the Lake Chad region.</p><p>Social, political, and economic organization of each state is examined. The role of Islam in the north and traditional religions in the south is covered. Students analyse the factors that contributed to the rise and decline of these states.</p>` },
    { topic: 'European Contact and the Trans-Atlantic Slave Trade',
      body: `<p>European contact with the Nigerian coast began in the 15th century with the Portuguese. Initially focused on trade in spices, gold, and pepper, it shifted to the trans-Atlantic slave trade — the forced transportation of millions of Africans to the Americas between the 16th and 19th centuries.</p><p>WAEC requires understanding of: the organization of the slave trade, the middle passage, the abolition movement (Wilberforce, Equiano), the effects of the slave trade on Nigerian societies (depopulation, political instability, economic decline), and the transition to legitimate commerce (palm oil, groundnuts).</p>` },
  ],
  'Christian Religious Studies': [
    { topic: 'The Nature of God and Creation',
      body: `<p>The CRS syllabus begins with the biblical understanding of God — His attributes: omnipotence (all-powerful), omniscience (all-knowing), omnipresence (everywhere), holiness, justice, love, and mercy. These attributes are derived from scripture.</p><p>The creation story (Genesis 1–2) presents God as the creator of heaven and earth. Humanity is created in the image of God (Imago Dei) — endowed with reason, moral awareness, and the capacity for relationship. The fall of man (Genesis 3) introduces sin into the world and sets the stage for God's redemptive plan. Students relate these teachings to contemporary issues.</p>` },
    { topic: 'Faith and Covenant',
      body: `<p>Faith is defined as trust and confidence in God. The example of Abraham — the father of faith — is studied in detail (Genesis 12–22). God's call, the promise of descendants, Abraham's journey, and the test of faith (sacrifice of Isaac). Abraham's faith was counted as righteousness (Genesis 15:6).</p><p>Covenant — a solemn agreement between God and His people. The Abrahamic covenant (circumcision as sign), the Mosaic covenant (the Ten Commandments at Sinai), and the Davidic covenant. The new covenant prophesied by Jeremiah and fulfilled in Jesus Christ. WAEC questions often compare these covenants.</p>` },
  ],
};

// ─── SS2 ─────────────────────────────────────────────────────────────────────

const SS2: Record<string, LessonDef[]> = {
  Commerce: [
    { topic: 'Wholesale and Retail Trade',
      body: `<p>This topic examines the middlemen in the distribution chain. Wholesalers buy in bulk from producers and sell in smaller quantities to retailers. The WAEC syllabus lists the functions of wholesalers: storage/bearing risk, breaking bulk, transportation, market information, credit, and promotion.</p><p>Retailers sell directly to final consumers. Types of retail trade: small-scale (itinerant, kiosk, corner shop, open market) and large-scale (supermarket, department store, chain store, hypermarket, mail order, online retail). Modern trends — e-commerce (Amazon, Jumia), cash-and-carry, and franchising — are covered with Nigerian examples.</p>` },
    { topic: 'Transportation and Communication in Commerce',
      body: `<p>Transportation is the physical movement of goods and persons from one place to another. The WAEC syllabus covers modes: road, rail, water, air, and pipeline. The advantages and disadvantages of each mode, and factors influencing choice (cost, speed, nature of goods, distance, reliability).</p><p>Communication — the transmission of information in business. Traditional (postal, courier, telegraph) and modern (telephone, fax, email, internet, video conferencing). The role of ICT in modern commerce — E-commerce, E-banking, E-payments — is emphasized. The importance of effective communication in business operations.</p>` },
  ],
  Accounting: [
    { topic: 'Cash Book and Bank Reconciliation',
      body: `<p>The cash book serves as both a journal and a ledger for cash and bank transactions. Three types: single-column (cash only), two-column (cash and bank), and three-column (cash, bank, and discount). WAEC expects students to prepare and balance a three-column cash book.</p><p>Bank reconciliation statement — a statement that explains the difference between the cash book balance and the bank statement balance. Reasons for differences: unpresented cheques, uncredited lodgements, bank charges, direct debits, standing orders, dividends collected. The step-by-step preparation of the reconciliation statement is practiced with examination-style questions.</p>` },
    { topic: 'Final Accounts of a Sole Trader',
      body: `<p>Final accounts are prepared at the end of an accounting period to determine profit or loss and the financial position. WAEC syllabus covers: (i) Trading Account — calculates gross profit (Sales − Cost of Goods Sold), (ii) Profit and Loss Account — calculates net profit (Gross Profit + Other Income − Expenses), (iii) Balance Sheet — shows assets, liabilities, and capital.</p><p>Key adjustments: prepayments (prepaid expenses), accruals (outstanding expenses), depreciation (straight-line and reducing balance methods), and bad debts. Students practice extracting figures from a trial balance and preparing the final accounts in proper format.</p>` },
  ],
  Economics: [
    { topic: 'Market Structure — Perfect Competition and Monopoly',
      body: `<p>Market structure describes the competitive environment in which firms operate. WAEC distinguishes between: (i) Perfect competition — many buyers and sellers, homogeneous products, free entry/exit, perfect information, price-taker firms. (ii) Monopoly — single seller, unique product, barriers to entry, price-maker.</p><p>Monopolistic competition and oligopoly are introduced briefly. Students compare the characteristics, advantages, and disadvantages of each structure. Diagrams showing short-run and long-run equilibrium under perfect competition and monopoly are drawn and interpreted. Price discrimination by monopolists is discussed with examples.</p>` },
    { topic: 'Money, Banking, and Financial Institutions',
      body: `<p>Money is defined by its functions: medium of exchange, unit of account, store of value, and standard of deferred payment. WAEC examines the characteristics (durability, portability, divisibility, homogeneity, stability, scarcity) and types of money (commodity, metallic, paper, bank deposits, electronic).</p><p>Central banking — the Central Bank of Nigeria (CBN) — its functions: currency issue, banker to government and banks, monetary policy (interest rate, reserve requirement, open market operations), lender of last resort, and financial stability. Commercial banks — functions (deposit-taking, lending, money transfer, foreign exchange) and the credit creation process.</p>` },
  ],
  'Business Studies': [
    { topic: 'Business Management and Administration',
      body: `<p>Management is the process of achieving organizational goals through planning, organizing, staffing, directing, and controlling. WAEC emphasizes management functions: planning (setting objectives and strategies), organizing (designing structure and allocating resources), staffing (recruiting, training, developing), directing (leading, motivating, communicating), and controlling (monitoring performance, corrective action).</p><p>Theories of management: scientific management (Taylor), administrative principles (Fayol), and human relations (Mayo). Leadership styles — autocratic, democratic (participative), and laissez-faire — are compared. Motivation theories: Maslow's hierarchy of needs and Herzberg's two-factor theory.</p>` },
    { topic: 'Business Communication and Correspondence',
      body: `<p>Communication is the transfer of information between parties. WAEC classifies communication: internal (within the organization) and external (outside). Channels: oral (face-to-face, telephone, meetings), written (letters, memos, reports, emails), and electronic (intranet, video conferencing). Barriers to effective communication (noise, language, cultural differences, organizational structure) and how to overcome them.</p><p>Business correspondence types: inquiry letters, quotation/estimate, order letters, invoice, delivery note, payment receipt, complaint letters, and adjustment letters. The correct format for each document is demonstrated with samples.</p>` },
  ],
  Biology: [
    { topic: 'Nutrition — Modes and Human Digestive System',
      body: `<p>Nutrition is the process by which organisms obtain and use food. WAEC distinguishes: autotrophic nutrition (photosynthesis in green plants) and heterotrophic nutrition (holozoic, saprophytic, parasitic, symbiotic).</p><p>The human digestive system: mouth (teeth, saliva, amylase), oesophagus (peristalsis), stomach (gastric juices, pepsin, HCl), small intestine (duodenum — bile, pancreatic juice; ileum — villi for absorption), large intestine (water reabsorption), and anus. Enzymes and their substrates (carbohydrases, proteases, lipases) are tabulated. The balanced diet — carbohydrates, proteins, fats, vitamins, minerals, water, fibre — and deficiency diseases (scurvy, rickets, kwashiorkor, anaemia).</p>` },
    { topic: 'Transport System in Animals — Circulation',
      body: `<p>Transport in animals is carried out by the circulatory system. The WAEC syllabus covers the structure of the mammalian heart — four chambers (right/left atria and ventricles), valves (tricuspid, bicuspid, semi-lunar), and major blood vessels (aorta, vena cava, pulmonary artery/vein).</p><p>The cardiac cycle: systole (contraction) and diastole (relaxation). Blood vessels: arteries (thick, elastic, carry blood away from heart), veins (thin, valves, carry blood towards heart), capillaries (one-cell thick for exchange). Composition of blood: plasma, red blood cells (erythrocytes — haemoglobin, oxygen transport), white blood cells (leucocytes — immunity), and platelets (thrombocytes — clotting). Double circulation — pulmonary and systemic — is explained with a diagram.</p>` },
  ],
  Chemistry: [
    { topic: 'Atomic Structure and Bonding',
      body: `<p>Atoms consist of protons, neutrons, and electrons. WAEC requires knowledge of: atomic number (Z = number of protons), mass number (A = protons + neutrons), and isotopes (atoms of the same element with different mass numbers). Electron configuration — electrons arranged in shells (K, L, M, N) following the 2n² rule.</p><p>Chemical bonding: ionic bonding (transfer of electrons between metals and non-metals — e.g., NaCl), covalent bonding (sharing of electrons between non-metals — e.g., H₂O, CH₄), metallic bonding (sea of delocalized electrons). Intermolecular forces: van der Waals forces and hydrogen bonding (H₂O, NH₃, HF). Relationship between bonding type and physical properties (melting/boiling point, electrical conductivity, solubility).</p>` },
    { topic: 'The Periodic Table',
      body: `<p>The Periodic Table is an arrangement of elements in order of increasing atomic number. WAEC expects students to: (i) identify periods (horizontal rows) and groups (vertical columns), (ii) locate metals, non-metals, and metalloids, (iii) explain periodicity — trends in atomic radius, ionization energy, electron affinity, and electronegativity across periods and down groups.</p><p>Group 1 (Alkali Metals) — reactivity increases down the group, reactions with water and oxygen. Group 7 (Halogens) — reactivity decreases down the group, colour trends, displacement reactions. Group 8 (Noble Gases) — inertness and uses (lighting, welding, cooling). Transition metals — variable oxidation states, coloured compounds, catalytic properties (Fe in Haber process, Ni in hydrogenation).</p>` },
  ],
  Physics: [
    { topic: 'Energy, Work, and Power',
      body: `<p>Work is defined as the product of force and distance in the direction of the force (W = F × d). Energy is the capacity to do work — kinetic energy (KE = ½mv²), potential energy (PE = mgh), and other forms (thermal, chemical, nuclear, electrical). The principle of conservation of energy: energy cannot be created or destroyed, only converted from one form to another.</p><p>Power is the rate of doing work (P = W/t = Fv). Practical applications: calculating the power output of machines (engines, pumps, electrical appliances). Efficiency = (useful output energy / total input energy) × 100%. WAEC questions typically involve calculations of work, KE, PE, and power in simple mechanical systems.</p>` },
    { topic: 'Waves — Properties and Light (Reflection and Refraction)',
      body: `<p>Waves are disturbances that transfer energy without transferring matter. WAEC classifies waves: mechanical (require a medium — sound, water waves) and electromagnetic (do not require a medium — light, radio). Properties common to all waves: reflection, refraction, diffraction, interference.</p><p>Light: laws of reflection (angle of incidence = angle of reflection), image formation by plane and curved mirrors (concave and convex). Refraction — Snell's law (n = sin i / sin r), refractive index, critical angle, and total internal reflection. Applications: periscope, telescope, fibre optics. The lens formula (1/f = 1/u + 1/v) and magnification (m = v/u) are used to solve problems.</p>` },
  ],
  Mathematics: [
    { topic: 'Trigonometry and Trigonometric Ratios',
      body: `<p>Trigonometry deals with relationships between angles and sides of triangles. WAEC covers the trigonometric ratios: sine, cosine, and tangent for acute angles in right-angled triangles. Exact values for 0°, 30°, 45°, 60°, and 90° must be memorized.</p><p>The sine rule (a/sin A = b/sin B = c/sin C) and cosine rule (a² = b² + c² − 2bc cos A) for non-right-angled triangles. Angles of elevation and depression — solving problems involving heights and distances. Bearings (three-figure notation) — reading and calculating bearings between points. Graphs of trigonometric functions — amplitude, period, and phase shift.</p>` },
    { topic: 'Statistics — Measures of Central Tendency and Dispersion',
      body: `<p>Statistics involves collecting, organizing, presenting, and analyzing data. WAEC requires calculation of: mean (x̄ = Σf x / Σf), median (middle value of ordered data), and mode (most frequent value). These are called measures of central tendency.</p><p>Measures of dispersion: range (highest − lowest), variance, and standard deviation (σ = √[Σf(x − x̄)² / Σf]). For grouped data, students estimate the mean using assumed mean or class midpoints. Cumulative frequency (ogive) curves are used to estimate median, quartiles, and percentiles. Interpreting data presented in tables, bar charts, pie charts, histograms, and frequency polygons.</p>` },
  ],
  'Basic Technology': [
    { topic: 'Forces, Structures, and Stability',
      body: `<p>Forces are pushes or pulls acting on objects. WAEC covers types of forces: tensile (pulling apart), compressive (pushing together), shear (sliding), torsional (twisting), and bending. The effects of forces on structures — tension, compression, shear, torsion, bending — are demonstrated with examples (bridges, buildings, chairs).</p><p>Structural stability: factors affecting stability — centre of gravity, base area, and weight distribution. Triangles as rigid shapes (trusses). The principle of moments: sum of clockwise moments = sum of anticlockwise moments. Levers — first class (seesaw), second class (wheelbarrow), third class (fishing rod) — and mechanical advantage calculations.</p>` },
    { topic: 'Simple Electrical Circuits and Components',
      body: `<p>Basic electricity for SS2: current (I) in amperes — the flow of electric charge, voltage (V) in volts — the driving force, resistance (R) in ohms — opposition to flow. Ohm's law: V = IR. Circuits are drawn with standard symbols (battery, resistor, lamp, switch, ammeter, voltmeter).</p><p>Series circuits — current is the same everywhere, voltages add up. Parallel circuits — voltage is the same across branches, currents add up. Calculations of total resistance in series (R_total = R₁ + R₂ + ...) and parallel (1/R_total = 1/R₁ + 1/R₂ + ...). Electrical power (P = VI = I²R) and energy consumption (E = Pt in kilowatt-hours). Safety — fuses, earthing, circuit breakers.</p>` },
  ],
  'Computer Studies': [
    { topic: 'Programming Fundamentals — Algorithms and Flowcharts',
      body: `<p>An algorithm is a step-by-step procedure for solving a problem. WAEC/NECO requires students to express algorithms using: (i) pseudocode — a human-readable description, (ii) flowcharts — a graphical representation using standard symbols (oval for start/end, parallelogram for input/output, rectangle for process, diamond for decision).</p><p>Control structures: sequence (steps executed in order), selection (if-then-else, case/switch), and iteration (repeat-until, while-do, for loop). Students write algorithms for simple problems — finding the largest of three numbers, calculating factorial, checking if a number is prime — and represent them as flowcharts.</p>` },
    { topic: 'Computer Software — Operating Systems and Applications',
      body: `<p>Software is classified into system software and application software. System software: operating systems (Windows, macOS, Linux, Android, iOS) — functions (process management, memory management, file management, device management, security). Utility programs — antivirus, disk defragmenter, backup utilities.</p><p>Application software: word processors (Microsoft Word), spreadsheets (Excel), presentation software (PowerPoint), databases (Access), web browsers, and graphic design tools. Students learn about file types (.docx, .xlsx, .pdf, .jpg, .mp4). The distinction between proprietary software (Microsoft Office, Adobe Photoshop), freeware, shareware, and open-source software (LibreOffice, GIMP, Linux) is discussed.</p>` },
  ],
  'Technical Drawing': [
    { topic: 'Orthographic Projection',
      body: `<p>Orthographic projection is the representation of 3D objects using 2D views — front elevation, plan (top view), and side (end) elevation. WAEC teaches both first-angle (European) and third-angle (American) projection systems. The symbol for each projection is drawn in the title block.</p><p>Students practice: (i) drawing the three principal views from a given isometric drawing, (ii) arranging views according to the projection system, (iii) hidden details as dashed lines, (iv) dimensioning with extension lines and arrowheads. Simple objects (stepped block, V-block, bearing bracket) are used for practice.</p>` },
    { topic: 'Isometric and Oblique Drawing',
      body: `<p>Isometric drawing uses a grid of 30° lines to show three faces of an object simultaneously. WAEC expects students to draw isometric views from given orthographic projections. Rules: all vertical lines remain vertical, horizontal lines are drawn at 30° to the horizontal, measurements along isometric axes are true scale.</p><p>Oblique drawing — a simpler pictorial where the front face is drawn true shape and receding lines are at 45°. Isometric and oblique drawings are compared. Students also practice dimensioning pictorial drawings and adding hidden details where appropriate.</p>` },
  ],
  'English Language': [
    { topic: 'Grammatical Structures — Tenses, Voice, and Speech',
      body: `<p>WAEC English Language paper heavily tests grammatical accuracy. This lesson covers: verb tenses — present, past, future (simple, continuous, perfect, perfect continuous) with their uses and time indicators.</p><p>Active and passive voice — transforming sentences between active and passive (e.g., "The boy kicked the ball" → "The ball was kicked by the boy"). Rules for tense consistency. Reported (indirect) speech — changes in tense, pronouns, and time expressions when converting direct speech ("She said, 'I am coming'" → "She said that she was going"). Other structures: conditional clauses (types 0, 1, 2, 3) and question tags.</p>` },
    { topic: 'Oral English — Vowels, Consonants, and Stress',
      body: `<p>Oral English carries separate marks in the WAEC examination. This lesson covers: the 12 pure vowels (monophthongs) — /iː/ (sheep), /ɪ/ (ship), /e/ (bed), /æ/ (cat), /ɑː/ (car), /ɒ/ (pot), /ɔː/ (port), /ʊ/ (book), /uː/ (boot), /ʌ/ (cup), /ɜː/ (bird), /ə/ (about). The 8 diphthongs — /eɪ/ (cake), /aɪ/ (bite), /ɔɪ/ (boy), /aʊ/ (house), /əʊ/ (goat), /ɪə/ (here), /eə/ (hair), /ʊə/ (poor). Consonant sounds (24 in English) with place and manner of articulation.</p><p>Word stress — the syllable that receives the most emphasis (e.g., PREsent vs. preSENT). Sentence stress — content words (nouns, verbs, adjectives) are stressed; function words (articles, prepositions, conjunctions) are usually unstressed. Intonation patterns — rising and falling tones for questions and statements.</p>` },
  ],
  'Literature-in-English': [
    { topic: 'Elements of Prose — Plot, Character, and Setting',
      body: `<p>Prose fiction includes novels and short stories. WAEC expects detailed analysis of prescribed texts. This lesson examines: plot — the sequence of events (exposition, rising action, climax, falling action, resolution). Types of plot (linear, episodic, circular). Subplots and flashbacks.</p><p>Characterization: protagonist, antagonist, round (complex), flat (simple), static (unchanging), and dynamic (changing). Methods of characterization — direct (author tells us) and indirect (speech, action, thoughts, reactions of others). Setting — time, place, and social environment of the story. The relationship between setting and theme is explored with reference to prescribed novels.</p>` },
    { topic: 'Elements of Drama',
      body: `<p>Drama is literature written for performance. WAEC focuses on: (i) plot structure in plays — acts, scenes, and the dramatic arc, (ii) characters — protagonist, antagonist, foil, chorus (in classical drama), (iii) dialogue and soliloquy, (iv) stage directions and their significance.</p><p>Dramatic techniques: flashback, foreshadowing, aside, dramatic irony, comic relief. Types of drama: tragedy (protagonist's downfall due to a fatal flaw — hamartia), comedy (light-hearted with happy ending), tragicomedy, and melodrama. Students analyze the prescribed drama text for theme, characterization, language, and relevance to society.</p>` },
  ],
  Government: [
    { topic: 'The Structure and Organs of Government',
      body: `<p>WAEC examines the three arms of government and the principle of separation of powers (Montesquieu). The legislature (parliament/National Assembly) — makes laws. Structures: unicameral (one house) vs. bicameral (two houses — Senate and House of Representatives in Nigeria). Functions: law-making, oversight of the executive, representation, approval of budgets.</p><p>The executive — implements laws. Composition (President, Vice-President, ministers, civil service). Functions: policy formulation, execution of laws, foreign diplomacy, appointment of officials. The judiciary — interprets laws. Structure (Supreme Court, Court of Appeal, High Courts, Sharia/Customary Courts). Functions: adjudication, constitutional interpretation, protection of rights. The rule of law (Dicey's conception) and judicial independence are emphasized.</p>` },
    { topic: 'Citizenship, Rights, and Responsibilities',
      body: `<p>Citizenship is the legal status that confers rights and obligations. WAEC distinguishes: citizenship by birth (jus soli), by descent (jus sanguinis), by registration (for Commonwealth citizens), and by naturalization. The Nigerian constitution defines the categories.</p><p>Fundamental human rights in the Nigerian Constitution (Chapter IV): right to life, dignity, personal liberty, fair hearing, private and family life, freedom of thought/conscience/religion, expression, assembly/association, movement, and freedom from discrimination. Limitations on these rights during emergencies. Corresponding responsibilities of citizens: loyalty to the nation, payment of taxes, obedience to laws, and national service.</p>` },
  ],
  History: [
    { topic: 'British Colonial Administration in Nigeria',
      body: `<p>The British colonial administration in Nigeria (1900–1960) is a core WAEC topic. The policy of indirect rule (Lugard) — ruling through traditional chiefs. Its application in the Northern Protectorate (success — existing centralized system) and the Eastern Region (failure — no centralized chiefs, Warrant Chiefs created resentment).</p><p>The amalgamation of 1914 — the merging of the Northern and Southern Protectorates into the Colony and Protectorate of Nigeria. Reasons: administrative convenience and economic integration. Consequences: improved infrastructure but also the foundation for ethnic and regional tensions. Nationalist movements — Herbert Macaulay (NNDP), Nnamdi Azikiwe (NCNC), Obafemi Awolowo (Action Group), Ahmadu Bello (NPC). Constitutional developments (Clifford 1922, Richards 1946, Macpherson 1951, Lyttleton 1954 leading to federalism).</p>` },
    { topic: 'The Rise of Nationalism and Independence Movements',
      body: `<p>Nationalism is the desire for self-government and independence from colonial rule. WAEC examines the factors that gave rise to nationalism in Nigeria: (i) education of Nigerians abroad (Azikiwe in US, Awolowo in UK), (ii) racial discrimination by colonial officials, (iii) the Atlantic Charter (1941) affirming the right to self-determination, (iv) the role of the press (Azikiwe's West African Pilot, Awolowo's Nigerian Tribune), (v) labour movements and the 1945 general strike.</p><p>Key nationalist organizations: Nigerian National Democratic Party (NNDP, 1923), National Youth Movement (NYM, 1936), National Council of Nigeria and the Cameroons (NCNC, 1944), Action Group (AG, 1951), Northern People's Congress (NPC, 1951). The London Constitutional Conferences (1953, 1957, 1958) leading to independence on October 1, 1960.</p>` },
  ],
  'Christian Religious Studies': [
    { topic: 'The Life and Ministry of Jesus Christ',
      body: `<p>WAEC CRS examines the life of Jesus as recorded in the four Gospels. The birth of Jesus — annunciation, nativity, visit of the Magi, presentation in the temple. The baptism of Jesus by John the Baptist and the temptation in the wilderness.</p><p>Jesus' public ministry: the calling of the twelve disciples, the Sermon on the Mount (Beatitudes, Lord's Prayer, teachings on love, forgiveness, and judgement), parables of the Kingdom (sower, mustard seed, prodigal son, good Samaritan), and miracles (healing — blind, lame, lepers; nature — calming the storm, walking on water; raising the dead — Lazarus). The transfiguration and Peter's confession of faith.</p>` },
    { topic: 'The Passion, Death, and Resurrection of Jesus',
      body: `<p>The final week of Jesus' earthly life: the triumphal entry into Jerusalem, the cleansing of the temple, the Last Supper (institution of the Eucharist), the betrayal by Judas, the agony in Gethsemane, the arrest, trial before the Sanhedrin and Pilate, the crucifixion and burial.</p><p>The resurrection on the third day — the empty tomb, appearances to Mary Magdalene, the disciples on the road to Emmaus, and to the apostles. The significance of the resurrection: victory over sin and death, validation of Jesus' divinity, and the foundation of Christian hope. The Great Commission (Matthew 28:18–20) — go and make disciples of all nations. The ascension into heaven.</p>` },
  ],
};

// ─── SS3 ─────────────────────────────────────────────────────────────────────

const SS3: Record<string, LessonDef[]> = {
  Commerce: [
    { topic: 'International Trade and Balance of Payments',
      body: `<p>International trade involves the exchange of goods and services across national boundaries. WAEC distinguishes between visible trade (physical goods — crude oil, agricultural products, manufactured goods) and invisible trade (services — banking, insurance, tourism, transportation). The balance of trade and the balance of payments are key concepts.</p><p>Balance of payments accounts: current account (exports, imports, income, transfers), capital and financial account (investment flows, loans). Reasons for deficits — over-reliance on imports, low export diversification. Remedial measures: import substitution, export promotion, trade protection (tariffs, quotas, subsidies), currency devaluation. International trade organizations: WTO, IMF, World Bank, ECOWAS, AU — their roles in promoting and regulating trade.</p>` },
    { topic: 'Business Finance and the Stock Exchange',
      body: `<p>Business finance covers the sources of funds for business operations. WAEC classifies sources: (i) by period — short-term (bank overdraft, trade credit, commercial papers), medium-term (loans, debentures, leasing), long-term (shares, retained earnings, bonds). (ii) by origin — internal (retained profit, sale of assets) and external (bank loans, share capital, government grants).</p><p>The Nigerian Stock Exchange (NSE) — the market for securities. Types: primary market (new issues — IPO, rights issue) and secondary market (trading of existing shares). Functions of the stock exchange: capital mobilization, investment opportunity, liquidity, price valuation, corporate governance. Stock market indicators (NSE All-Share Index). Insurance — principles (indemnity, insurable interest, utmost good faith, subrogation, contribution) and types (life, fire, marine, motor, accident).</p>` },
  ],
  Accounting: [
    { topic: 'Depreciation and Disposal of Fixed Assets',
      body: `<p>Depreciation is the reduction in the value of a fixed asset over its useful life due to wear and tear, obsolescence, or the passage of time. WAEC covers three methods: (i) Straight-line — equal annual charge (Cost − Residual Value) / Useful Life. (ii) Reducing balance — fixed percentage of the diminishing book value, higher charges in earlier years. (iii) Revaluation method — used for assets like livestock, loose tools.</p><p>Accounting for depreciation: provision for depreciation account (accumulated depreciation). Disposal of fixed assets — the disposal account (debit: asset cost; credit: accumulated depreciation and proceeds from sale; the balancing figure is profit or loss on disposal). Examination questions often require the preparation of the asset account, provision for depreciation account, and disposal account.</p>` },
    { topic: 'Accounts of Non-Profit Organizations and Companies',
      body: `<p>Non-profit organizations (clubs, societies, churches) prepare different financial statements: Receipts and Payments Account (summary of cash transactions — cash basis) and Income and Expenditure Account (accrual basis — surplus = income over expenditure, deficit = expenditure over income). The Balance Sheet is called the Statement of Affairs.</p><p>Company accounts: types of capital — authorized, issued, called-up, paid-up, and uncalled capital. Reserves — revenue reserves (retained profits) and capital reserves (share premium, revaluation surplus). Preparation of the final accounts of a company — Trading, Profit and Loss Account, and appropriation section (dividend distribution, transfer to reserves). The Balance Sheet of a company — share capital, reserves, long-term liabilities, current liabilities, fixed assets, current assets.</p>` },
  ],
  Economics: [
    { topic: 'National Income and Economic Development',
      body: `<p>National income is the total value of goods and services produced in an economy in a given period. WAEC requires understanding of the circular flow of income (households, firms, government, foreign sector) and the three approaches to measurement: (i) output (value added), (ii) income (factor incomes — wages, rent, interest, profit), (iii) expenditure (consumption + investment + government spending + net exports).</p><p>GDP (Gross Domestic Product — within the country), GNP (Gross National Product — including net income from abroad), and NI (National Income). Problems of measurement: informal sector, double counting, inflation. Economic growth (increase in real GDP) vs. development (improvement in living standards, education, health, infrastructure). Factors promoting growth: capital accumulation, technological progress, human capital development, institutional quality.</p>` },
    { topic: 'International Economics — Trade, Aid, and Development',
      body: `<p>International economics examines economic relations between countries. WAEC covers comparative advantage (Ricardo) — countries benefit from specializing in goods where they have lower opportunity cost. Terms of trade — the ratio of export prices to import prices. Deteriorating terms of trade for developing countries (Prebisch-Singer hypothesis).</p><p>Foreign aid — bilateral and multilateral, tied and untied. Arguments for and against foreign aid. International economic organizations: IMF (balance of payments support, conditionality), World Bank (development projects), WTO (trade rules, dispute resolution). Economic integration: ECOWAS (stages — free trade area, customs union, common market). The role of Nigeria in ECOWAS, OPEC, and the African Union is discussed.</p>` },
  ],
  'Business Studies': [
    { topic: 'Entrepreneurship and Business Creation',
      body: `<p>Entrepreneurship is the process of identifying business opportunities and organizing resources to create a business venture. WAEC emphasizes: entrepreneurial traits (initiative, risk-taking, innovation, perseverance, self-confidence), sources of business ideas (market gap, personal interest, technological change, franchise), and the business planning process.</p><p>The business plan — executive summary, company description, market analysis, organizational structure, product/service description, marketing plan, financial projections (startup costs, revenue forecast, break-even analysis). Sources of startup capital: personal savings, loans (family/friends, banks, microfinance), grants, venture capital, crowdfunding. Legal and regulatory requirements: business registration (CAC), tax registration (TIN), permits and licences. Government support agencies: SMEDAN, NAFDAC, SON.</p>` },
    { topic: 'Consumer Protection and Market Regulation',
      body: `<p>Consumer protection involves laws and institutions that safeguard consumers from unfair trade practices. WAEC lists consumer rights: right to safety, to be informed, to choose, to be heard, to redress, to consumer education, and to a healthy environment. Corresponding responsibilities: critical awareness, responsible consumption, environmental awareness.</p><p>Consumer protection agencies in Nigeria: Consumer Protection Council (CPC — now FCCPC), National Agency for Food and Drug Administration and Control (NAFDAC — regulates food, drugs, cosmetics, medical devices), Standards Organization of Nigeria (SON — product quality standards). The role of trade associations (MAN, NACCIMA) in self-regulation. Advertising standards — false/deceptive advertising and legal remedies. Consumer credit protection.</p>` },
  ],
  Biology: [
    { topic: 'Genetics — Inheritance and Variation',
      body: `<p>Genetics is the study of heredity — how traits are passed from parents to offspring. WAEC covers Mendel's laws of inheritance: (i) Law of Segregation — alleles separate during gamete formation, (ii) Law of Independent Assortment — alleles of different genes sort independently. Monohybrid cross (3:1 ratio in F₂) and dihybrid cross (9:3:3:1 ratio) are analyzed with Punnett squares.</p><p>Dominant and recessive alleles, genotype (homozygous, heterozygous) and phenotype. Incomplete dominance (snapdragon — pink flowers), codominance (ABO blood groups — multiple alleles, three alleles I^A, I^B, i). Sex determination (XX female, XY male) and sex-linked inheritance (haemophilia, colour blindness — carried on X chromosome). Variation — continuous (height, weight — polygenic) and discontinuous (blood group, tongue rolling — single gene). Mutations — gene (sickle cell) and chromosomal (Down syndrome).</p>` },
    { topic: 'Evolution and Adaptation',
      body: `<p>Evolution is the process of gradual change in species over generations. WAEC covers the theory of evolution by natural selection (Charles Darwin): variation exists in populations, individuals with advantageous traits survive and reproduce, over time the population changes. Evidence for evolution: (i) fossil record (transitional forms — Archaeopteryx), (ii) comparative anatomy (homologous structures — forelimbs of mammals, analogous structures — wings of birds/insects), (iii) molecular biology (DNA sequence similarities), (iv) biogeography.</p><p>Adaptation — structural (camouflage, mimicry, thick fur in cold climates), physiological (hibernation, estivation, salt glands in marine birds), and behavioural (migration, courtship rituals). Adaptation to aquatic, terrestrial, and aerial environments. Natural selection in action — antibiotic resistance in bacteria, industrial melanism in peppered moths. Speciation — allopatric (geographic isolation) and sympatric (reproductive isolation).</p>` },
  ],
  Chemistry: [
    { topic: 'Organic Chemistry — Hydrocarbons and Functional Groups',
      body: `<p>Organic chemistry is the study of carbon compounds. WAEC covers the homologous series: (i) Alkanes (CₙH₂ₙ₊₂) — single bonds, saturated, methane, ethane, propane. Substitution reactions with halogens. (ii) Alkenes (CₙH₂ₙ) — double bond, unsaturated, ethene (C₂H₄). Addition reactions — hydrogenation (to alkanes), hydration (to alcohols), polymerization (polyethene). (iii) Alkynes (CₙH₂ₙ₋₂) — triple bond, ethyne (C₂H₂).</p><p>Functional groups: alcohols (−OH, ethanol from fermentation), aldehydes (−CHO, methanal), ketones (>C=O, propanone), carboxylic acids (−COOH, ethanoic acid — vinegar), esters (−COO−, fruity smells, used as flavourings). IUPAC nomenclature for naming organic compounds up to six carbon atoms. Test for functional groups using chemical tests (Fehling's for aldehydes, iodoform test for methyl ketones).</p>` },
    { topic: 'Reaction Rates and Chemical Equilibrium',
      body: `<p>Reaction rates measure how fast reactants are converted to products. WAEC identifies factors affecting rates: (i) concentration — higher concentration, more collisions, faster rate, (ii) temperature — higher temperature increases kinetic energy and collisions (roughly doubles rate per 10°C rise), (iii) surface area — powdered solids react faster, (iv) catalysts — speed up reactions without being consumed (enzymes, transition metals).</p><p>Collision theory: particles must collide with sufficient energy (activation energy — Eₐ) and correct orientation. Catalysts lower activation energy by providing an alternative pathway. Chemical equilibrium — a reversible reaction where forward and reverse rates are equal. Le Chatelier's principle: if a system at equilibrium is disturbed, it shifts to counteract the disturbance. Factors: concentration, temperature, pressure (for gases). The Haber process (ammonia synthesis — 450°C, 200 atm, iron catalyst) as an industrial application.</p>` },
  ],
  Physics: [
    { topic: 'Electromagnetism',
      body: `<p>Electromagnetism studies the relationship between electricity and magnetism. WAEC covers: (i) magnetic fields of a current-carrying conductor — right-hand grip rule, (ii) force on a current-carrying conductor in a magnetic field (Fleming's left-hand rule — motor effect), (iii) electromagnetic induction — Faraday's law (induced e.m.f. is proportional to the rate of change of magnetic flux), Lenz's law (induced current opposes the change producing it).</p><p>Applications: the electric motor (converts electrical energy to mechanical), the generator/dynamo (converts mechanical to electrical — AC generator uses slip rings, DC generator uses split-ring commutator), the transformer (step-up/step-down — Vₚ/Vₛ = Nₚ/Nₛ, efficiency). Alternating current (AC) — peak and r.m.s. values (V_rms = V₀/√2). Power transmission — why high voltage is used (reduces I²R losses).</p>` },
    { topic: 'Atomic and Nuclear Physics',
      body: `<p>Atomic physics examines the structure of the atom at the quantum level. WAEC covers: Rutherford's alpha-scattering experiment (discovery of the nucleus), Bohr's model (electrons in fixed energy levels), and the concept of energy level transitions (emission and absorption spectra).</p><p>Radioactivity — the spontaneous emission of radiation from unstable nuclei. Types: alpha (α — helium nucleus, stopped by paper, highly ionizing), beta (β — fast electron, stopped by aluminium), gamma (γ — high-energy photon, stopped by lead, weakly ionizing). Decay equations — writing nuclear equations for alpha and beta decay. Half-life (t₁/₂) — the time for half a sample to decay, calculations using the formula N = N₀(½)ⁿ or graphical determination from decay curves. Applications: carbon-14 dating, medical tracers (technetium-99m), radiotherapy (cobalt-60). Nuclear fission (chain reaction, nuclear power) and fusion (energy of the sun). Safety precautions for handling radioactive materials.</p>` },
  ],
  Mathematics: [
    { topic: 'Calculus — Differentiation and Applications',
      body: `<p>Calculus is the mathematics of change. Differentiation: the derivative of a function y = f(x) is denoted dy/dx or f'(x) and represents the rate of change. The gradient function from first principles. Derivatives of polynomial functions: if y = xⁿ, dy/dx = nxⁿ⁻¹. Rules: constant multiple, sum/difference, product rule, quotient rule, chain rule (for composite functions).</p><p>Applications: (i) finding gradients of curves at a point, (ii) determining where a function is increasing or decreasing (dy/dx > 0 increasing, dy/dx < 0 decreasing), (iii) stationary points (dy/dx = 0) — maxima, minima, and points of inflection (using second derivative or sign table), (iv) optimization — solving problems involving maximum profit, minimum cost, maximum area. Integration (indefinite — reverse of differentiation, definite — area under a curve between limits).</p>` },
    { topic: 'Coordinate Geometry and Vectors',
      body: `<p>Coordinate geometry (also called analytic geometry) applies algebra to geometry. WAEC covers: the distance between two points (d = √[(x₂−x₁)² + (y₂−y₁)²]), midpoint formula ((x₁+x₂)/2, (y₁+y₂)/2), gradient/slope (m = (y₂−y₁)/(x₂−x₁)), equation of a straight line (y − y₁ = m(x − x₁) or y = mx + c). Conditions for parallel lines (m₁ = m₂) and perpendicular lines (m₁ × m₂ = −1).</p><p>Vectors — a vector has magnitude and direction. Notation: (x, y) or ai + bj. Addition, subtraction, and scalar multiplication. Magnitude (|v| = √(x² + y²)). Position vectors. Unit vectors. The scalar (dot) product (a·b = |a||b|cosθ) and its use to determine perpendicularity (a·b = 0). Vector applications: displacement, velocity, force, and relative motion.</p>` },
  ],
  'Basic Technology': [
    { topic: 'Electronics — Semiconductors and Basic Components',
      body: `<p>Electronics is the branch of technology that deals with the flow of electrons in circuits containing semiconductor devices. WAEC introduces semiconductors — materials with conductivity between conductors and insulators. Doping produces n-type (excess electrons) and p-type (excess holes) semiconductors.</p><p>The PN junction diode — allows current in one direction only (forward bias = conducts, reverse bias = blocks). Applications: rectification (converting AC to DC — half-wave and full-wave rectifier, bridge rectifier). The transistor (NPN, PNP) — current amplifier. The transistor as a switch. Simple electronic circuits: LED circuits, light-dependent resistor (LDR) circuits for automatic lights. Soldering and PCB (printed circuit board) assembly. Safety when handling electronic components (ESD protection).</p>` },
    { topic: 'Energy Systems and Power Generation',
      body: `<p>Energy systems cover the generation, transmission, and distribution of power. WAEC syllabus includes: sources of energy — fossil fuels (coal, oil, natural gas — non-renewable), nuclear, hydroelectric, solar, wind, geothermal, biomass (renewable). Nigeria's energy mix — gas-fired thermal plants (Egbin, Delta), hydroelectric dams (Kainji, Shiroro, Jebba).</p><p>The national grid — the interconnected system of power generation, transmission (high voltage — 330kV, 132kV using step-up/step-down transformers), and distribution (11kV, 415V, 230V for consumers). Factors affecting power supply: transmission losses (I²R), maintenance, load shedding. Energy conservation practices — energy-efficient appliances, turning off unused devices, improved insulation. Alternative energy for rural areas — solar home systems, mini-hydro, biogas digesters.</p>` },
  ],
  'Computer Studies': [
    { topic: 'Data Structures and File Organization',
      body: `<p>Data structures are ways of organizing data for efficient use. WAEC covers: arrays (one-dimensional and two-dimensional — accessing elements by index), records (a collection of related fields — e.g., student name, age, class), lists (linear and linked), stacks (LIFO — Last In, First Out, push/pop operations), queues (FIFO — First In, First Out, enqueue/dequeue).</p><p>File organization: (i) serial — records in no particular order, (ii) sequential — records in a specific order (e.g., by student ID), (iii) direct/random access — using a key to calculate storage address (hashing method). File types: master files (permanent data — student records, payroll), transaction files (temporary updates — daily sales), backup files. Database management systems (DBMS) — relational (tables with relationships), SQL (SELECT, INSERT, UPDATE, DELETE queries).</p>` },
    { topic: 'Computer Networking and Cybersecurity',
      body: `<p>Networking connects multiple computers to share resources and information. WAEC covers: network topologies (star — central hub, bus — single cable, ring — closed loop, mesh — every device connected to every other). Network types: LAN (local — building), MAN (metropolitan — city), WAN (wide — country/global, e.g., the Internet).</p><p>Network protocols: TCP/IP (Transmission Control Protocol/Internet Protocol — the Internet's foundation), HTTP/HTTPS (web), FTP (file transfer), SMTP/POP3 (email), DNS (Domain Name System — translates domain names to IP addresses). IP addressing (IPv4 — 32-bit, e.g., 192.168.1.1; IPv6 — 128-bit). Cybersecurity threats: malware (virus, worm, trojan, ransomware), phishing, DoS/DDoS attacks, Man-in-the-Middle. Countermeasures: firewalls, antivirus software, encryption (SSL/TLS), strong passwords, two-factor authentication, regular backups.</p>` },
  ],
  'Technical Drawing': [
    { topic: 'Building Drawing — Plans and Elevations',
      body: `<p>Building drawing applies technical drawing to architectural design. WAEC syllabus includes: required views for a building — floor plan (top view showing rooms, doors, windows), elevations (front, side, rear — showing external appearance), and sections (cut-through views showing internal structure — foundations, walls, roof).</p><p>Conventions: doors (swing arc indicating direction), windows (lines showing pane divisions), stairs (plan and sectional representation), sanitary fittings (WC, sink, bath). Dimensions — overall building dimensions, room sizes, door/window openings. Symbols for materials in section: concrete (dots), brick (hatch), earth (random pattern). Site plans — showing building location, boundaries, access roads, drainage. Students draw a complete set of building drawings for a simple bungalow.</p>` },
    { topic: 'Engineering Drawing — Sections and Assembly',
      body: `<p>Engineering drawing communicates design information for manufacturing. WAEC covers sectioning — cutting through objects to reveal internal features. Types: full section, half section, offset section, revolved section, removed section. Section lines (hatching) — thin, evenly spaced, at 45° for the same part.</p><p>Assembly drawings — showing how parts fit together. The bill of materials (BOM) — part number, description, quantity, material. Exploded views — parts separated along assembly axis. Dimensioning for manufacturing: tolerances (limits, fits — clearance, interference, transition), surface finish symbols (Ra values), welding symbols. Computer-Aided Design (CAD) — an introduction to using 2D and 3D CAD software (AutoCAD, SolidWorks) for creating digital drawings. Advantages of CAD: speed, accuracy, ease of modification, 3D visualization, integration with CAM (Computer-Aided Manufacturing).</p>` },
  ],
  'English Language': [
    { topic: 'Summary Writing — Skills and Strategies',
      body: `<p>Summary writing tests the ability to extract and restate the main ideas of a passage in concise form. WAEC summary questions: (i) identify the main points in a passage (usually two or three), (ii) express each point in a complete sentence in your own words, (iii) avoid repetition, examples, and direct quotations unless required.</p><p>Strategies: (i) read the question first to know what information to extract, (ii) scan the passage for relevant points, (iii) use your own words — avoid copying the author's phrasing, (iv) keep to the stated number of sentences, (v) watch for the word limit. Common marking schemes: each correct point = 1 mark, clear expression = 1 mark, use of own words = 1 mark. Practice passages are worked through in class with model answers.</p>` },
    { topic: 'Examination Techniques and Past Question Practice',
      body: `<p>Final revision for the WASSCE/NECO English Language paper. Lesson covers: Paper 1 (Objective — 60 multiple-choice questions on comprehension, lexis, structure, oral English). Tips — answer the easier questions first, eliminate obviously wrong options, manage time (approximately 1 minute per question).</p><p>Paper 2 (Essay, Comprehension, Summary): (i) choose your essay question wisely — pick the type you are most confident with, (ii) spend 5 minutes planning your essay outline, (iii) allocate time — essay (45 min), comprehension (30 min), summary (30 min), leave 5 min for review, (iv) use good English — correct grammar, varied vocabulary, proper punctuation and paragraphing. Paper 3 (Oral English — test of orals). Common pitfalls to avoid: incomplete answers, going off-topic, poor handwriting, leaving questions unanswered. Practice with past WAEC questions.</p>` },
  ],
  'Literature-in-English': [
    { topic: 'Poetry Analysis — Themes, Techniques, and Context',
      body: `<p>In-depth poetry analysis for the WAEC examination. Poems are analyzed under: (i) subject matter — what is the poem about at a literal level? (ii) theme — the central idea or message (love, death, injustice, nature, identity), (iii) mood/tone — the poet's attitude (joyful, melancholic, angry, reflective), (iv) diction — choice of words and their connotations, (v) imagery — the mental pictures created, (vi) sound devices — rhyme, rhythm, alliteration, assonance, onomatopoeia, (vii) poetic devices — simile, metaphor, personification, irony, symbolism, apostrophe.</p><p>Students analyze selected WAEC-prescribed poems from the anthology. Essay structure for poetry: introduction (poet, title, theme), body (analysis stanza by stanza with textual evidence), conclusion (overall significance and personal response). Common pitfalls: retelling the poem instead of analyzing it, not supporting claims with quotations, ignoring context (historical, cultural, biographical).</p>` },
    { topic: 'General Revision and Examination Practice',
      body: `<p>Comprehensive revision for the WAEC Literature-in-English examination. The paper structure: Paper 2 (Prose — 2 essay questions on each of the three prescribed novels), Paper 3 (Drama — 2 essay questions on each of the three prescribed plays), Paper 4 (Poetry — 1 essay on the appreciation of a poem from the anthology).</p><p>Revision strategies: (i) re-read each prescribed text at least once in the term, (ii) create character profiles and thematic summaries for each text, (iii) memorize key quotes (at least 5 per text), (iv) practice past questions under timed conditions, (v) understand the marking scheme — content (knowledge of text) and expression (quality of writing), (vi) for unseen poetry in Paper 4, identify the theme, tone, and at least three literary devices. Sample answers are reviewed and scored using WAEC standard rubrics.</p>` },
  ],
  Government: [
    { topic: "Nigeria's Foreign Policy",
      body: `<p>Foreign policy is the strategy a state uses to achieve its objectives in international relations. WAEC examines Nigeria's foreign policy since independence (1960). Principles: (i) non-alignment — not siding with either the US or USSR during the Cold War, (ii) Afrocentricity — Africa as the centrepiece of Nigeria's foreign policy, (iii) peaceful dispute resolution, (iv) respect for sovereignty and territorial integrity, (v) promotion of economic cooperation.</p><p>Phases: (i) 1960–1966 (conservative, pro-West, moderate role in Africa — Balewa), (ii) 1970–1975 (active African leadership — Gowon, African liberation, OAU), (iii) 1975–1979 (Murtala/Obasanjo — radical, anti-apartheid, nationalization of British Petroleum), (iv) 1979–1983 (Shagari — economic diplomacy, technical aid to Africa), (v) 1985–1993 (Babangida — return to Afrocentrism), (vi) 1999–present (Obasanjo, Yar'Adua, Jonathan, Buhari — economic diplomacy, anti-corruption, counter-terrorism). Nigeria's roles in ECOWAS, AU, UN Peacekeeping, OPEC, and the Commonwealth.</p>` },
    { topic: 'International Organizations and Nigeria\'s Role',
      body: `<p>International organizations are institutions established by treaties between states. WAEC syllabus covers: (i) The United Nations (UN) — purposes (peace, security, development, human rights), principal organs (General Assembly, Security Council — 5 permanent members with veto, ECOSOC, ICJ, Secretariat). Nigeria's contributions to UN peacekeeping missions (Liberia, Sierra Leone, Darfur).</p><p>(ii) The African Union (AU) — formerly OAU, established 2002. Objectives: continental integration, peace and security, development. Organs: Assembly of Heads of State, Commission, Peace and Security Council. (iii) ECOWAS — established 1975. Aims: economic integration (common market, single currency — Eco), peace and security (ECOMOG — Liberia, Sierra Leone). (iv) OPEC — Organization of Petroleum Exporting Countries. Nigeria joined 1971. Role in stabilizing oil prices through production quotas. (v) The Commonwealth — voluntary association of former British colonies. Benefits: technical assistance, cultural exchange, Commonwealth Games.</p>` },
  ],
  History: [
    { topic: 'Post-Independence Nigeria (1960–1979)',
      body: `<p>Nigeria gained independence on October 1, 1960, as a federation of three regions (Northern, Eastern, Western). The First Republic (1960–1966): parliamentary system, Nnamdi Azikiwe (Governor-General/President), Abubakar Tafawa Balewa (Prime Minister). Achievements: expansion of education (UNN, ABU), infrastructure development. Challenges: political instability — the census crisis (1962/63), Action Group crisis (1962), the Tiv riots, the 1964 federal election crisis.</p><p>The January 15, 1966 military coup — Major Kaduna Nzeogwu (first military coup in Nigeria). The counter-coup of July 1966 — Lt. Col. Yakubu Gowon became Head of State. The Aburi Accord (Ghana) — failed attempt at confederation. The declaration of Biafran secession (May 30, 1967, Odumegwu Ojukwu) and the Nigerian Civil War (1967–1970). The war ended with General Gowon's policy of "no victor, no vanquished." Reconstruction and the Second National Development Plan. The coup of July 29, 1975 — General Murtala Mohammed assumed power (Murtala/Obasanjo regime: creation of 7 new states, local government reform, indigenization decree, "Operation Feed the Nation"). Assassination of Murtala (Feb 1976). Obasanjo completed the transition to civilian rule — 1979 Constitution and the Second Republic.</p>` },
    { topic: 'Nigeria from 1979 to the Present',
      body: `<p>The Second Republic (1979–1983): President Shehu Shagari (NPN). Presidential system with 19 states. Achievements — Green Revolution (agriculture), housing programmes. Collapse due to widespread corruption, declining oil revenue, and the disputed 1983 election (rigging allegations). The December 31, 1983 coup — General Buhari (Military: "War Against Indiscipline" — WAI). The August 27, 1985 coup — General Babangida (IBB). The Structural Adjustment Programme (SAP — 1986, currency devaluation, privatization). The transition programme cancelled, the June 12, 1993 presidential election (MKO Abiola, Basorun — annulled by Babangida).</p><p>The Interim National Government (ING — Ernest Shonekan, August–November 1993). The November 17, 1993 coup — General Sani Abacha (repressive regime, human rights abuses, political prisoners). Abacha's sudden death (June 8, 1998) — General Abdulsalami Abubakar. Transition to civilian rule — the 1999 Constitution, General Obasanjo elected President (1999–2007). The Fourth Republic: Obasanjo (anti-corruption — EFCC, ICPC; economic reforms — debt relief $18 billion — from Paris Club). Yar'Adua (2007–2010 — amnesty for Niger Delta militants, Umaru Yar'Adua 's illness and Doctrine of Necessity, Goodluck Jonathan became President). Jonathan (2010–2015 — aviation reform, transformation agenda, corruption in oil subsidy, security challenges — Boko Haram). Buhari (2015–2023 — anti-corruption, fight against insurgency, economic recession, social investment programmes — N-Power, TraderMoni). Contemporary issues: restructuring debate, resource control, ethnic and religious tensions, and Nigeria's evolving democracy.</p>` },
  ],
  'Christian Religious Studies': [
    { topic: 'The Early Church — Acts of the Apostles',
      body: `<p>WAEC CRS covers the birth and growth of the early Church as recorded in Acts. The Day of Pentecost (Acts 2) — the Holy Spirit descends on the apostles, speaking in tongues, Peter's sermon, 3,000 converts. Characteristics of the early Church: devotion to apostles' teaching, fellowship, breaking of bread, prayer, communal living (sharing of possessions), signs and wonders.</p><p>Persecution and expansion: Peter and John before the Sanhedrin (Acts 4), Ananias and Sapphira (Acts 5), the appointment of the seven deacons (Stephen — Acts 6), Stephen's martyrdom (Acts 7) — the first Christian martyr. The persecution under Saul of Tarsus led to the scattering of believers and the spread of the Gospel to Samaria (Philip and the Ethiopian eunuch — Acts 8). The conversion of Saul (Acts 9) — on the road to Damascus, his transformation into Paul the apostle. The Council of Jerusalem (Acts 15) — resolving the Gentile controversy (circumcision not required). Paul's missionary journeys (Acts 13–28) — spreading the Gospel across Asia Minor, Macedonia, Greece, and Rome.</p>` },
    { topic: 'Christian Ethics and Social Responsibility',
      body: `<p>Christian ethics — the study of right and wrong conduct based on biblical principles. WAEC examines the teachings of Jesus and the epistles on moral issues. The Sermon on the Mount (Matthew 5–7) — the Beatitudes (attitudes for kingdom living), teachings on anger, adultery, divorce, oaths, retaliation, love for enemies, prayer (the Lord's Prayer), fasting, wealth, worry, and judgement.</p><p>Pauline ethics: Christians as new creations in Christ (2 Corinthians 5:17), the fruit of the Spirit (Galatians 5:22–23 — love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control) vs. the works of the flesh (Galatians 5:19–21). Social issues: Christian marriage (Ephesians 5 — mutual submission, love, respect), the role of civil authorities (Romans 13 — obey government), wealth and poverty (1 Timothy 6:10 — love of money as root of evil, the parable of the rich fool, the good Samaritan — care for neighbours). Justice, mercy, forgiveness, and reconciliation as marks of Christian discipleship.</p>` },
  ],
};

// ─── Seed runner ─────────────────────────────────────────────────────────────

async function seed() {
  console.log('🌱 Seeding WAEC/NECO-aligned lessons...\n');

  const existing = await sql.query('SELECT COUNT(*) as count FROM lessons');
  const count = Number(existing[0]?.count ?? 0);
  if (count > 0) {
    console.log(`  ⚠️  ${count} lesson(s) already exist. Deleting old data...`);
    await sql.query('DELETE FROM flagged_qa');
    await sql.query('DELETE FROM lesson_progress');
    await sql.query('DELETE FROM artifact_content');
    await sql.query('DELETE FROM lessons');
    console.log('  ✅ Cleared.\n');
  }

  const allData: Record<string, Record<string, LessonDef[]>> = { SS1, SS2, SS3 };
  let total = 0;

  for (const level of ['SS1', 'SS2', 'SS3'] as const) {
    const subjects = allData[level];
    for (const [subject, lessons] of Object.entries(subjects)) {
      const department = departmentOf(subject);
      for (const lesson of lessons) {
        const title = `${level} ${subject} — ${lesson.topic}`;
        // Build description: plain text excerpt from body
        const desc = lesson.body
          .replace(/<[^>]+>/g, '')
          .substring(0, 160)
          .replace(/\s+/g, ' ')
          .trim() + '...';

        const content = `<h2 class="text-xl font-bold mb-4">${lesson.topic}</h2>\n<div class="space-y-4 text-gray-700 leading-relaxed">\n${lesson.body}\n</div>\n`;

        await sql.query(
          `INSERT INTO lessons (title, description, content, class_level, department)
           VALUES ($1, $2, $3, $4, $5)`,
          [title, desc, content, level, department]
        );
        total++;
      }
    }
    console.log(`  📚 ${level}: inserted ${Object.values(subjects).flat().length} lessons`);
  }

  console.log(`\n✅ Done! ${total} WAEC/NECO-aligned lessons inserted.`);
}

seed().catch((err) => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
